server:
  servlet:
    context-path: /ecom-user
  port: 8091
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${USER_DB_URL:jdbc:mysql://localhost:3306/e_user_mgt}
    username: ${USER_DB_USERNAME:root}
    password: ${USER_DB_PASSWORD:}
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: validate
  flyway:
    enabled: true
    validate-on-migrate: true
  cloud:
    stream:
      bindings:
        output:
          destination: user
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
app:
  name: ecom-user

services:
  order-mgt:
    url: ${ORDER_URL:http://localhost:8090/ecom-od}

